@startuml
abstract class IBinaryTreeComponent{
    -int value
    +{abstract}void NRL()
    +{abstract} void addLeft(IBinaryTreeComponent c)
    +{abstract}void addRight(IBinaryTreeComponent c)
    +{abstract}void remove(IBinaryTreeComponent c)
}
class InternalNode
class LeafNode

IBinaryTreeComponent <|.. LeafNode
IBinaryTreeComponent <|.. InternalNode
InternalNode --> IBinaryTreeComponent: left
InternalNode --> IBinaryTreeComponent: right

@enduml