@startuml
'https://plantuml.com/class-diagram

enum Candidate{
    DONALD_TRUMP, JOE_BIDEN
}
class Election{
    - {static} Election instance
    - int trump, biden
    - List<String> voteUsers
    - Election()
    + {static} Election getInstance()
    # void vote(Candidate c, String userId)
    + void myPrint()
}

class User{
    - String id
    + void vote(Candidate c)
}

User ..> Election




@enduml