@startuml
'https://plantuml.com/class-diagram

class Builder{
-String cpu, ram, storage, screen
+Builder buildCPU(String CPU)
+Builder buildRAM(String ram)
+Builder buildStorage(String storage)
+Builder buildScreen(String screen)
+Computer build()

}
class Computer {
- String cpu, ram, storage, screen
- Computer(Builder b)
}

Builder ..> Computer
@enduml